### ISSUE TITLE
Priority Queue

### ISSUE THREAD

**Issue by pascalhelmer** [pascalhelmer/screeps#1]
We shouldn't write this ourself. Perhaps we should one of the following libs:
- https://www.npmjs.com/package/ts-priority-queue
- https://github.com/basarat/typescript-collections

**Comment by pascalhelmer** [comment]
@5kilian ???

**Comment by 5kilian** [comment]
A priority queue will be needed in our game mechanic scheduler. Even if I would prefere to have our own implementation I am in to save some time and use the already done ones, but only if we do not need a specific implementation. But imo the scheduler will have that specific mechanic and will use a simple standard queue so.

A I find the ts-priority-queue minimalistic, I would probably prefere the bigger version typescript-collections, because it seams to be more active and more extensive.

**Comment by 5kilian** [comment]
Please link the npm packages not the github links next time, because the information about the weekly downloads and the dependencies are more important than the code. The GitHub link is still linked on the npmjs page at the same place in every project.

https://www.npmjs.com/package/typescript-collections
